name: deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set variables
      id: vars
      run: |
        echo ::set-output name=docker_image::docker.pkg.github.com/${{ github.repository }}/master:$(git rev-parse --short=7 ${{ github.sha }})
        echo ::set-output name=commit_message::$(git log --format=%B -n 1)
    - name: Build docker image
      run: |
        docker build . --file Dockerfile --tag ${{ steps.vars.outputs.docker_image }}
    - name: Login to registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
    - name: Push docker image
      run: |
        docker push ${{ steps.vars.outputs.docker_image }}
    - name: Deploy
      run: >
        curl -s --fail -X POST -H 'Content-Type: application/json' -H 'Authorization: Basic ${{ secrets.deployToken }}' -d '{"repository":"${{ github.repository }}","dockerImage":"${{ steps.vars.outputs.docker_image }}","branch":"${{ github.ref }}"}' https://galleon.pekle.lv/deploy
    - name: Notify deploy
      continue-on-error: true
      run: >
        curl -s --fail
        -X POST
        -H 'Content-Type: application/json'
        -d '{"content":"```Deployed. Repo: ${{ github.repository }} Image: ${{ steps.vars.outputs.docker_image }} Last Commit: ${{steps.vars.outputs.commit_message}}```"}'
        ${{ secrets.webhookUrl }}
